// File generated by FlutterFire CLI.
// Run: flutterfire configure
// Replace these values with your actual Firebase project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── REPLACE ALL VALUES BELOW WITH YOUR FIREBASE PROJECT CONFIG ───────────
  // Run `flutterfire configure` to auto-generate this file for your project.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ2zAy1_P09akDAZ5gxDpNzVYXQu_er0c',
    appId: '1:163900820680:web:96625f958612924b9b29fd',
    messagingSenderId: '163900820680',
    projectId: 'employee-manager-c5783',
    authDomain: 'employee-manager-c5783.firebaseapp.com',
    storageBucket: 'employee-manager-c5783.firebasestorage.app',
    measurementId: 'G-0SX2KN9DVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB52I8EBUOj1TWArhImSLCAVbLxudDlO-0',
    appId: '1:163900820680:android:42c82d1262dc96899b29fd',
    messagingSenderId: '163900820680',
    projectId: 'employee-manager-c5783',
    storageBucket: 'employee-manager-c5783.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDJdjGMIg8-7I2ZLNNwRPqLtp4_jm95I',
    appId: '1:163900820680:ios:f1a4ade26c9a31689b29fd',
    messagingSenderId: '163900820680',
    projectId: 'employee-manager-c5783',
    storageBucket: 'employee-manager-c5783.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementApplicationFlutterAssessment',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFDJdjGMIg8-7I2ZLNNwRPqLtp4_jm95I',
    appId: '1:163900820680:ios:f1a4ade26c9a31689b29fd',
    messagingSenderId: '163900820680',
    projectId: 'employee-manager-c5783',
    storageBucket: 'employee-manager-c5783.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagementApplicationFlutterAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ2zAy1_P09akDAZ5gxDpNzVYXQu_er0c',
    appId: '1:163900820680:web:c054f832bbef430f9b29fd',
    messagingSenderId: '163900820680',
    projectId: 'employee-manager-c5783',
    authDomain: 'employee-manager-c5783.firebaseapp.com',
    storageBucket: 'employee-manager-c5783.firebasestorage.app',
    measurementId: 'G-NGTDC3WXEG',
  );
}
