// Mocks generated by Mockito 5.4.6 from annotations
// in employee_management_application_flutter_assessment/test/widget/employee_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:employee_management_application_flutter_assessment/framwork/repository/contract/i_auth_repository.dart'
    as _i4;
import 'package:employee_management_application_flutter_assessment/framwork/repository/contract/i_employee_repository.dart'
    as _i6;
import 'package:employee_management_application_flutter_assessment/framwork/repository/model/employee_model/employee_model.dart'
    as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmployeeModel_1 extends _i1.SmartFake implements _i3.EmployeeModel {
  _FakeEmployeeModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i4.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i2.User?>.empty(),
          )
          as _i5.Stream<_i2.User?>);

  @override
  _i5.Future<_i2.UserCredential> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> registerWithEmail(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmail, [
              email,
              password,
              displayName,
            ]),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#registerWithEmail, [
                  email,
                  password,
                  displayName,
                ]),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<_i2.UserCredential> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i5.Future<_i2.UserCredential>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [IEmployeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIEmployeeRepository extends _i1.Mock
    implements _i6.IEmployeeRepository {
  MockIEmployeeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.EmployeeModel>> getAllEmployees() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEmployees, []),
            returnValue: _i5.Future<List<_i3.EmployeeModel>>.value(
              <_i3.EmployeeModel>[],
            ),
          )
          as _i5.Future<List<_i3.EmployeeModel>>);

  @override
  _i5.Future<_i3.EmployeeModel> getEmployeeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeById, [id]),
            returnValue: _i5.Future<_i3.EmployeeModel>.value(
              _FakeEmployeeModel_1(
                this,
                Invocation.method(#getEmployeeById, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.EmployeeModel>);

  @override
  _i5.Future<_i3.EmployeeModel> createEmployee(_i3.EmployeeModel? employee) =>
      (super.noSuchMethod(
            Invocation.method(#createEmployee, [employee]),
            returnValue: _i5.Future<_i3.EmployeeModel>.value(
              _FakeEmployeeModel_1(
                this,
                Invocation.method(#createEmployee, [employee]),
              ),
            ),
          )
          as _i5.Future<_i3.EmployeeModel>);

  @override
  _i5.Future<_i3.EmployeeModel> updateEmployee(
    String? id,
    _i3.EmployeeModel? employee,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmployee, [id, employee]),
            returnValue: _i5.Future<_i3.EmployeeModel>.value(
              _FakeEmployeeModel_1(
                this,
                Invocation.method(#updateEmployee, [id, employee]),
              ),
            ),
          )
          as _i5.Future<_i3.EmployeeModel>);

  @override
  _i5.Future<void> deleteEmployee(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmployee, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
