// Mocks generated by Mockito 5.4.6 from annotations
// in employee_management_application_flutter_assessment/test/unit/employee_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:employee_management_application_flutter_assessment/framwork/repository/model/employee_model/employee_model.dart'
    as _i2;
import 'package:employee_management_application_flutter_assessment/framwork/repository/repository/employee_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEmployeeModel_0 extends _i1.SmartFake implements _i2.EmployeeModel {
  _FakeEmployeeModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EmployeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmployeeRepository extends _i1.Mock
    implements _i3.EmployeeRepository {
  MockEmployeeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.EmployeeModel>> getAllEmployees() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEmployees, []),
            returnValue: _i4.Future<List<_i2.EmployeeModel>>.value(
              <_i2.EmployeeModel>[],
            ),
          )
          as _i4.Future<List<_i2.EmployeeModel>>);

  @override
  _i4.Future<_i2.EmployeeModel> getEmployeeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployeeById, [id]),
            returnValue: _i4.Future<_i2.EmployeeModel>.value(
              _FakeEmployeeModel_0(
                this,
                Invocation.method(#getEmployeeById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.EmployeeModel>);

  @override
  _i4.Future<_i2.EmployeeModel> createEmployee(_i2.EmployeeModel? employee) =>
      (super.noSuchMethod(
            Invocation.method(#createEmployee, [employee]),
            returnValue: _i4.Future<_i2.EmployeeModel>.value(
              _FakeEmployeeModel_0(
                this,
                Invocation.method(#createEmployee, [employee]),
              ),
            ),
          )
          as _i4.Future<_i2.EmployeeModel>);

  @override
  _i4.Future<_i2.EmployeeModel> updateEmployee(
    String? id,
    _i2.EmployeeModel? employee,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmployee, [id, employee]),
            returnValue: _i4.Future<_i2.EmployeeModel>.value(
              _FakeEmployeeModel_0(
                this,
                Invocation.method(#updateEmployee, [id, employee]),
              ),
            ),
          )
          as _i4.Future<_i2.EmployeeModel>);

  @override
  _i4.Future<void> deleteEmployee(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmployee, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
